name: Pharos Analysis

on:
  workflow_dispatch:
  push:
    branches: [ main, pharos ]

jobs:
  analyze:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { exename: BEASTS.EXE, methods: '-n 46C060 --delete-method 46C110' }
          - { exename: DKII.EXE, methods: '-n 634E80 --delete-method 6341B0 -n 57CEB0 --delete-method 57D0B0 -n 61ECA0 --delete-method 61ED10' }
          - { exename: patch.dll, methods: '' }
          - { exename: QMIXER95.DLL, methods: '' }
    runs-on: ubuntu-26.04
    env:
      IMAGE: ghcr.io/trass3r/pharos:master-amd64 # seipharos/pharos
    steps:
      - uses: actions/checkout@v7
      - run: docker pull $IMAGE
      - uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 64
      - uses: Trass3r/workflow-telemetry-action@master
      - if: matrix.exename == 'DKII.EXE'
        run: |
          sed -i 's/QMIXER95.DLL/QMIXER.DLL/g' myapi.json
      - name: Cache Artifacts
        uses: Trass3r/cache-action@main
        with:
          path: |
            *.ser
            *.pl
          key: artifacts-${{ matrix.exename }}-${{ github.sha }}-${{ github.run_attempt }}
          restore-keys: |
            artifacts-${{ matrix.exename }}-${{ github.sha }}-
            artifacts-${{ matrix.exename }}-
      - name: partition
        run: |
          [ -s *.ser ] && exit 0
          docker run --rm -v `pwd`:/workspace -w /workspace $IMAGE \
            partition --serialize=${{ matrix.exename }}.ser --maximum-memory=78000 ${{ matrix.exename }}
      - name: analysis
        run: |
          [ -s *.facts.pl ] && exit 0
          docker run --rm -v `pwd`:/workspace -w /workspace $IMAGE \
            ooanalyzer --verbose=4 --timing --threads=4 --maximum-memory=78000 --per-function-maximum-memory=20000 --per-function-timeout=10000 \
              --serialize ${{ matrix.exename }}.ser -F ${{ matrix.exename }}.facts.pl \
              ${{ matrix.methods }} \
              --apidb=contrib/winmm.json --apidb /workspace/myapi.json ${{ matrix.exename }}
      - name: ooprolog
        run: |
          awk -F\( '{print $1}' *.facts.pl | sort | uniq -c
          [ -s *.results.pl ] && exit 0
          docker run --rm -v `pwd`:/workspace -w /workspace $IMAGE \
            ooprolog --log-level=4 --facts ${{ matrix.exename }}.facts.pl --results ${{ matrix.exename }}.results.pl
      - name: json
        run: |
          docker run --rm -v `pwd`:/workspace -w /workspace $IMAGE \
            ooprolog --log-level=4 --results ${{ matrix.exename }}.results.pl --json ${{ matrix.exename }}.json
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: results-${{ matrix.exename }}
          path: |
            ${{ matrix.exename }}.*
