name: RevNG Analysis

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install RevNG
        run: |
          df -h
          sudo rm -rf /usr/local/lib/android
          sudo apt autoremove -qq azure* dotnet* google* temurin* *-jre* '*llvm*' moby*
          df -h
          cd
          curl -L -s https://rev.ng/downloads/revng-distributable/master/install.sh | bash
          echo "$HOME/revng" >> $GITHUB_PATH
      - uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 64
      - name: Install Linux perf
        run: |
          set -eux
          sudo apt update
          sudo apt install -y linux-tools-common linux-tools-generic
          # Ensure perf can be run without sudo
          sudo sysctl -w kernel.perf_event_paranoid=0
          sudo sysctl -w kernel.kptr_restrict=0

          git clone --depth=1 https://github.com/brendangregg/FlameGraph.git

      - uses: catchpoint/workflow-telemetry-action@v2
      - name: Run analysis
        run: |
          set -eux
          perf record -F 99 -g -o perf.data -- revng analyze --resume=revngworkspace revng-initial-auto-analysis DKII.EXE
          perf report -i perf.data > perf_report.txt
          perf script -i perf.data | FlameGraph/stackcollapse-perf.pl > out.perf-folded
          FlameGraph/flamegraph.pl out.perf-folded > flamegraph-analysis.svg

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: analysis-results
          path: |
            revngworkspace/
            flamegraph-analysis.svg
            perf.data
            perf_report.txt
            out.perf-folded

      - name: Run decompilation
        run: |
          set -eux
          perf record -F 99 -g -o perf.data -- revng artifact --resume=revngworkspace decompile-to-single-file DKII.EXE | revng ptml > decompiled.ptml
          perf report -i perf.data > perf_report.txt
          perf script -i perf.data | FlameGraph/stackcollapse-perf.pl > out.perf-folded
          FlameGraph/flamegraph.pl out.perf-folded > flamegraph-decompile.svg

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: decompile-results
          path: |
            revngworkspace/
            decompiled.ptml
            flamegraph-decompile.svg
            perf.data
            perf_report.txt
            out.perf-folded
